apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-user-deployment
  labels:
    app: taskflow-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskflow-user
  template:
    metadata:
      labels:
        app: taskflow-user
    spec:
      containers:
      - name: user-svc
        image: 383189130746.dkr.ecr.us-east-1.amazonaws.com/taskflow-user:26793775988
        ports:
        - containerPort: 8001

